# .github/actions/wait-for-workflow/action.yml
name: Wait for Workflow
description: Waits until another workflow completes
inputs:
  workflow:
    description: "Workflow name to wait for"
    required: true
  branch:
    description: "Branch name"
    required: true
    default: ${{ github.head_ref }}
runs:
  using: "composite"
  steps:
    - name: Wait for ${{ inputs.workflow }}
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        echo "⏳ Waiting for '${{ inputs.workflow }}' on branch ${{ inputs.branch }}..."
        while true; do
          run_info=$(gh run list \
            --repo "${{ github.repository }}" \
            --workflow "${{ inputs.workflow }}" \
            --branch "${{ inputs.branch }}" \
            --event pull_request \
            --json status,conclusion \
            --jq '.[0]')

          status=$(echo "$run_info" | jq -r .status)
          conclusion=$(echo "$run_info" | jq -r .conclusion)

          echo "Current status: $status / $conclusion"

          if [[ "$status" == "completed" && "$conclusion" == "success" ]]; then
            echo "✅ Workflow succeeded!"
            break
          elif [[ "$status" == "completed" ]]; then
            echo "❌ Workflow failed or cancelled"
            exit 1
          fi

          sleep 20
        done
