name: Running flow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  test-line:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here
          echo "Tests completed."