name: Running flow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
permissions:
  contents: read
  statuses: write
jobs:
  test-line:
    runs-on: ubuntu-latest
    steps:
        - run: echo "This is a test line"