name: Second Workflow

on:
  pull_request:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read
  contents: read

jobs:
  wait-for-first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for First Workflow
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@399-feat-add-composite-action-for-workflow-dispatch-in-pr-builds
        with:
          workflow: "run_first.yml"
          # sha: ${{ github.sha }}

          token: ${{ secrets.GITHUB_TOKEN }}
          # pr-number: ${{ github.event.pull_request.number }}

  second:
    needs: wait-for-first
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Running Second Workflow after First"



