name: Run Opensearch Pipeline

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  debug:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' && 
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Get PR data
        uses: actions/github-script@v8
        id: pr-data
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${github.event.workflow_run.head_branch}`,
              state: 'open'
            });
            
            if (pullRequests.length === 0) {
              throw new Error('No open PR found for head branch: ' + github.event.workflow_run.head_branch);
            }
            
            const pr = pullRequests[0];
            console.log('Found PR:', pr.number);
            console.log('Head branch:', pr.head.ref);
            console.log('Base branch:', pr.base.ref);
            console.log('Head SHA:', pr.head.sha);
            
            return {
              number: pr.number,
              head_branch: pr.head.ref,
              base_branch: pr.base.ref,
              head_sha: pr.head.sha
            };
            
      - name: Show PR info
        run: |
          echo "PR Number: ${{ fromJson(steps.pr-data.outputs.result).number }}"
          echo "Head Branch: ${{ fromJson(steps.pr-data.outputs.result).head_branch }}"
          echo "Base Branch: ${{ fromJson(steps.pr-data.outputs.result).base_branch }}"
          echo "Head SHA: ${{ fromJson(steps.pr-data.outputs.result).head_sha }}"
          
  #   uses: Netcracker/qubership-terraform-hub/.github/workflows/ec2-control.yml@main
  #   with:
  #     instance_id: ${{ vars.AWS_GITHUB_RUNNER_ID }}
  #     action: "start"
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Opensearch-Pipeline:
  #   if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
  #   needs: start-self-hosted-runner
  #   uses: Netcracker/qubership-test-pipelines/.github/workflows/opensearch.yaml@e75a24c6a1e5d843de60674e9a395ecb003f5cf3
  #   with:
  #     service_branch: "${{ github.event.workflow_run.head_branch }}"
  #     versions_file: ".github/versions.yaml"
  #     pipeline_branch: "e75a24c6a1e5d843de60674e9a395ecb003f5cf3" #this value must match the value after '@' in 'uses'
  #     runner_type: "self-hosted"
  #   secrets:
  #     AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
  #     AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}

  # stop-self-hosted-runner:
  #   if: always() && github.event.workflow_run.event == 'pull_request'
  #   needs: Opensearch-Pipeline
  #   uses: Netcracker/qubership-terraform-hub/.github/workflows/ec2-control.yml@main
  #   with:
  #     instance_id: ${{ vars.AWS_GITHUB_RUNNER_ID }}
  #     action: "stop"
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
