name: Second Workflow

on:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  wait-for-first:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for First Workflow
        uses: netcracker/qubership-workflow-hub/actions/wait-on-workflow@399-feat-add-composite-action-for-workflow-dispatch-in-pr-builds
        with:
          workflow: "First Workflow"
          poll-interval-seconds: 10
          timeout-minutes: 30


  second:
    needs: wait-for-first
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Running Second Workflow after First"
