name: Second Workflow

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  wait-for-first:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - name: Wait for First Workflow
        id: wait
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@main
        with:
          workflow: "dev_build.yml"
          token: ${{ secrets.GITHUB_TOKEN }}

  second:
    needs: wait-for-first
    if: ${{ needs.wait-for-first.outputs.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Running Second Workflow after First"
