name: Run tests

permissions:
  contents: read
  pull-requests: read
  statuses: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Running tests..."