name: Second Workflow
permissions:
    contents: read

    pull-requests: read
    statuses: write

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
env:
    GITHUB_TOKEN: ${{ github.token }}

jobs:
    wait-for-first:
        runs-on: ubuntu-latest
        steps:
            - name: Wait for First Workflow
              run: |
                  gh run watch \
                  --repo "${{ github.repository }}" \
                  --workflow "First Workflow" \
                  --branch "${{ github.head_ref }}" \
                  --exit-status
        env:
            GH_TOKEN: ${{ github.token }}
    second:
        needs: wait-for-first
        runs-on: ubuntu-latest
        steps:
            - run: echo "🚀 Running Second Workflow after First"
