name: Second Workflow
permissions:
    contents: read

    pull-requests: read
    statuses: write

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
env:
    GITHUB_TOKEN: ${{ github.token }}

jobs:
    wait-for-first:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/wait-for-workflow
              with:
                  workflow: "First Workflow"
                  branch: ${{ github.head_ref }}
    second:
        needs: wait-for-first
        runs-on: ubuntu-latest
        steps:
            - run: echo "🚀 Running Second Workflow after First"
